---
- name: create mesos zookeeper list
  template: src=zookeeper-hosts.j2 dest=/etc/mesos/zk

- name: add haproxy mararthon file
  template: src=haproxymarathon.j2 dest=/etc/haproxy-marathon-bridge/marathons

- name: start haproxy
  service: name=haproxy state=started
  ignore_errors: true
